### ISSUE TITLE
拉取抛错

### ISSUE THREAD

**Issue by liuqiba** [onewhitethreee/zhihu_tools#3]
执行命令如下：
python3 .\answer_spider_.py -u https://www.zhihu.com/question/314003841/answer/1268928560

什么都没有修改情况下抛错 ，找不到目录“/www/bloghu/_posts/{}-{}-{}”

修改为 “with open(r'test.md'.format(now,answer_without_interrogation,generate_code()),'w+',encoding='utf-8') as fx:”

之后程序执行成功，但是test.md里面只有 文章的标题，内容全空

输出：
”https://www.zhihu.com/question/314003841/answer/1268928560
excerpt是：
已成功保存在post文件夹下’

**Comment by onewhitethreee** [comment]
需要修改一下xpath的获取规则，知乎改了
