### ISSUE TITLE
文章获取报错

### ISSUE THREAD

**Issue by Liuxc2005** [onewhitethreee/zhihu_tools#4]
D:\tools\zhihu_tools-main>python ./market.py -u https://www.zhihu.com/answer/2598756743
https://www.zhihu.com/answer/2598756743
Traceback (most recent call last):
  File "./market.py", line 22, in <module>
    title = html_xpath.xpath('/html/body/main/div/h1/text()')[0]
IndexError: list index out of range

**Comment by Liuxc2005** [comment]
可能是cookie的问题？是用z_c0这个吗？

**Comment by lrz2662061323** [comment]
你这个是超出list大小  可以用append的方法解决   但是解决了 这个代码依旧无法爬下来爽文
