### ISSUE TITLE
哥们 哥们   他失效了   爬不下来

### ISSUE THREAD

**Issue by lrz2662061323** [onewhitethreee/zhihu_tools#5]
跪求帮助

**Comment by onewhitethreee** [comment]
知乎规则改了很久了 没用了已经

**Comment by lrz2662061323** [comment]
谢谢

**Comment by kaka4554** [comment]
> 知乎规则改了很久了 没用了已经

现在可以爬了吗,我看大佬两天前更新了

**Comment by onewhitethreee** [comment]
> > 知乎规则改了很久了 没用了已经
> 
> 现在可以爬了吗,我看大佬两天前更新了


在我上传的那天是可以的，后面我被封号了。还没搞到号研究不了，不过理论上是还可以的

**Comment by Toki-Haruka** [comment]
兄弟兄弟，我的软件运行成功了，但是爬下来的只是文件名正确的空文档，这是我的问题嘛？
