### ISSUE TITLE
pTagList是空的

### ISSUE THREAD

**Issue by Carrotecho** [onewhitethreee/zhihu_tools#9]

**Comment by Carrotecho** [comment]
然后‘manuscript’这个字段里的文章文本都是有些错乱的，不知道咋回事

**Comment by onewhitethreee** [comment]
那就是知乎的文章换到其他标签了。从新改一下获取的位置就好了

**Comment by xjp342023125** [comment]
> _No description provided._

contents = content["appContext"]["__connectedAutoFetch"]["manuscript"]["data"]["manuscriptData"]["manuscript"] # 获取内容
